apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
type: Opaque
data:
  mysql-root-password: YWpheTEyMzQ1Njc4   # ajay12345678
  mysql-user: YWpheQ==                    # ajay
  mysql-password: YWpheTEyMzQ1Njc4OQ==    # ajay123456789
