apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: todo
spec:
  type: NodePort  # Use NodePort for environments without LoadBalancer support
  ports:
  - port: 80
    nodePort: 30080  # Optional: Specify a custom NodePort; otherwise, Kubernetes will assign one
  selector:
    app: wordpress
